### ISSUE TITLE
Powershell script with parameter

### ISSUE THREAD

**Issue by VermaDileep** [puppetlabs/puppetlabs-powershell#109]
How we can call powershell script with parameter.
  exec
  { 'ExecuteSQL':
    command => 'C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -executionpolicy remotesigned -Command C:\Utility\ExecuteSQL.ps1 -dataSource ${dataSource} -database $initialCatalog -UserName $dbadminuserid -password $dbadminpassword -SQLfilepath $databaseMSSQLScriptpath',
  returns => ['0','1'],
  logoutput => on_failure,
  }
is not working.It send with blank paramter value

**Comment by jpogran** [comment]
Since your command is in single quotes, I think puppet is not interpolating the variables for you. If you replace your single quotes with double quotes, this should work. You're also missing {} around some of the variables.

Also you are technically not using the puppet powershell module, you're using the cmd shell exec provider. We can simplify your exec by using the powershell exec provider:

```
exec{ 'ExecuteSQL':
  command => "C:\Utility\ExecuteSQL.ps1 -dataSource ${dataSource} -database ${initialCatalog} -UserName ${dbadminuserid} -password ${dbadminpassword} -SQLfilepath ${databaseMSSQLScriptpath}",
  returns => ['0','1'],
  logoutput => on_failure,
  provider => 'powershell'
}
```

**Comment by jpogran** [comment]
Closing this. If you have anymore issues you can ask in https://ask.puppet.com/questions or open a ticket in https://tickets.puppetlabs.com/browse/MODULES
