### ISSUE TITLE
require_relative breaks puppet 3.x running ruby 1.8.7

### ISSUE THREAD

**Issue by smallsam** [puppetlabs/puppetlabs-powershell#116]
#74 introduced use of require_relative which breaks in our shared windows/linux puppet master environment.

The linux environment runs Puppet 3.8.6 with Ruby 1.8.7 which I understand doesn't support require_relative. Is it possible to rewrite the require to maintain support for Ruby 1.8.7?

**Comment by smallsam** [comment]
Looking at your release numbering, it looks like I can revert to 1.0.6 to maintain support for ruby 1.8.7. Feel free to close, if you are dropping ruby 1.8.7 support.

**Comment by Iristyle** [comment]
@smallsam we landed a change in #114 to address this.  Our intent with module version `2.y` was that it was considered breaking, but due to requirements on the PowerShell version.  The breakage to open source Linux agents running atop 1.8.7 was accidental - some more discussion happened on #110 

For now, you may pin to the older `1.0.6`, until we cut the next `2.y` release, which should be within a few weeks.


Thanks!
