### ISSUE TITLE
Run script with parameters

### ISSUE THREAD

**Issue by vedmichv** [puppetlabs/puppetlabs-powershell#48]
How can I pass parameters to the script when using template as a source? Thanks
```
exec { 'rename-guest':
  command   => template('guest/rename-guest.ps1') "SOME PARAMETERS",
  onlyif    => template('guest/guest-exists.ps1'),
  provider  => powershell,
  logoutput => true,
}
```

**Comment by joshcooper** [comment]
One option is to interpolate variables in your erb template as described in https://docs.puppetlabs.com/guides/templating.html#referencing-variables

The other option is to use puppet's new heredoc support. You must use the future parser, i.e. `parser=future` in puppet 3.x. That way you can specify the powershell content directly inline with parameters/variables. The best explanation I can find is https://github.com/puppetlabs/armatures/blob/master/arm-4.heredoc/heredoc.md

**Comment by ferventcoder** [comment]
I'm going to close this as answered since it relates to documentation. If you feel that this is still an issue, or have not found a way to make it work, please feel free to comment on this issue or file a bug at https://tickets.puppetlabs.com/browse/MODULES

**Comment by lquantz** [comment]
Does the erb interpolation work when the template is a powershell script, as in the example above?  For example, in my manifest/class definition I define a variable like `$ipaddress = "129.33.25.111"` and in the powershell script itself I write out:
`Write-Host "My ipaddress is " <%= @ipaddress %> `
..but output text simply reads `My ipaddress is`

**Comment by ferventcoder** [comment]
@lquantz The file must be under `templates/` folder for that to work.

**Comment by ferventcoder** [comment]
https://docs.puppetlabs.com/puppet/latest/reference/lang_template_erb.html may be helpful.

**Comment by PeterHiggins** [comment]
I would like this to be re-opened as an issue. Though interpolating variables into a template of the powershell script is a possible work around it is not an ideal solution. In effect you are forced to modify the powershell script such that it will no longer function as a  standalone powershell script so that you can use it with puppet. This results in having to maintain two different versions of powershell scripts, one that cannot accept parameters and one that can. It would be far more useful to be able to simply pass parameters to the script.

**Comment by ferventcoder** [comment]
@PeterHiggins This is being discussed currently - https://tickets.puppetlabs.com/browse/MODULES-3447. JIRA is our issues system, so head over and vote/comment there.
