### ISSUE TITLE
add -file parameter

### ISSUE THREAD

**Issue by KarelSyrovatka** [puppetlabs/puppetlabs-powershell#70]
The powershell module runs ps scripts with -Command parameter.
 
e.g.
"C:\Windows\system32\WindowsPowershell\v1.0\powershell.exe" -ExecutionPolicy Bypass -Command - < "C:\puppet-powershell-accounts.ps1" 

This redirect powershell's stdin to read from a file causes the problem with PSConsoleHostReadLine search across a folder structure that finally causes the issue with high CPU utilization.
 
Could you add possibility to use -file instead of -command parameter?

Let me know If you need more info. I can send you a complete communication that I had with MS support.

Thanks,
Karel

**Comment by ferventcoder** [comment]
@KarelSyrovatka we already have an issue logged for issues surrounding the use of stdin redirect to pass in the command - https://tickets.puppetlabs.com/browse/MODULES-2634. If you feel they are different, please log a different ticket on JIRA. Thanks.

**Comment by ferventcoder** [comment]
As a followup, we log all work through our ticketing system JIRA. It appears we haven't closed the issues section here yet (probably an oversight). We ask that all tickets be created in JIRA to allow for work planning and triage to occur. Otherwise we might miss work that needs to occur, such as this issue.
